# Generated by Django 5.1.6 on 2025-02-21 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название книги')),
                ('image', models.ImageField(upload_to='book_images', verbose_name='загрузить картинку книги')),
                ('description', models.TextField(verbose_name='Описание книги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ценна')),
                ('release_date', models.DateField(verbose_name='Дата выхода')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genre', models.CharField(choices=[('Фантастика', 'Фантастика'), ('Детектив', 'Детектив'), ('Роман', 'Роман'), ('Поэзия', 'Поэзия'), ('Проза', 'Проза'), ('Детская литература', 'Детская литература'), ('Ужасы', 'Ужасы'), ('Приключения', 'Приключения'), ('Фэнтези', 'Фэнтези'), ('Научная фантастика', 'Научная фантастика'), ('Драма', 'Драма'), ('Комедия', 'Комедия')], max_length=50, verbose_name='Жанр')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта автора')),
                ('author', models.CharField(max_length=255, verbose_name='Имя автора')),
                ('trailer', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео из ютуб')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stars', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Library_kg.bookmodel')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
